# Generated by Django 3.2.25 on 2025-04-10 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at_epoch', models.IntegerField(null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the blog post.', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, help_text='Title of the blog post.', max_length=255, null=True)),
                ('body', models.TextField(blank=True, help_text='Main content of the blog post.', null=True)),
                ('description', models.CharField(blank=True, help_text='Short summary or description of the blog post.', max_length=255, null=True)),
                ('category', models.CharField(blank=True, help_text='Category or tag to classify the blog post (e.g., Tech, Lifestyle, News).', max_length=100, null=True)),
            ],
            options={
                'db_table': 'blogpost_table',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
    ]
