# Generated by Django 3.2.25 on 2025-04-10 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogpost_management', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='author',
            field=models.ForeignKey(help_text='User who authored the blog post.', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user_management.users'),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogpost_management.status'),
        ),
    ]
